// This code was generated by the Gardens Point Parser Generator
// Copyright (c) Wayne Kelly, QUT 2005-2010
// (see accompanying GPPGcopyright.rtf)

// GPPG version 1.5.0
// Machine:  AARON-PC
// DateTime: 3/23/2013 8:18:31 PM
// UserName: Aaron
// Input file <Blam\Scripting\Analysis\LispScriptParser.y - 3/23/2013 8:18:29 PM>

// options: lines gplex

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text;
using QUT.Gppg;
using System.Diagnostics;

namespace Blamite.Blam.Scripting.Analysis
{
public enum LispScriptTokens {error=45,EOF=46,GLOBAL=47,OBJECT=48,
    SCRIPT=49,NAME=50,FLOAT=51,STRING=52,BOOLEAN=53,NONE=54};

public struct ValueType
#line 7 "Blam\Scripting\Analysis\LispScriptParser.y"
{
#line 8 "Blam\Scripting\Analysis\LispScriptParser.y"
    public float FloatValue;
#line 9 "Blam\Scripting\Analysis\LispScriptParser.y"
    public string StringValue;
#line 10 "Blam\Scripting\Analysis\LispScriptParser.y"
    public bool BooleanValue;
#line 11 "Blam\Scripting\Analysis\LispScriptParser.y"
    public IScriptNode Node;
#line 12 "Blam\Scripting\Analysis\LispScriptParser.y"
    public List<IScriptNode> NodeList;
#line 13 "Blam\Scripting\Analysis\LispScriptParser.y"
    public ScriptDefinitionParam Parameter;
#line 14 "Blam\Scripting\Analysis\LispScriptParser.y"
    public List<ScriptDefinitionParam> ParamList;
#line 15 "Blam\Scripting\Analysis\LispScriptParser.y"
}
// Abstract base class for GPLEX scanners
public abstract class LispScriptScanBase : AbstractScanner<ValueType,LexLocation> {
  private LexLocation __yylloc = new LexLocation();
  public override LexLocation yylloc { get { return __yylloc; } set { __yylloc = value; } }
  protected virtual bool yywrap() { return true; }
}

// Utility class for encapsulating token information
public class ScanObj {
  public int token;
  public ValueType yylval;
  public LexLocation yylloc;
  public ScanObj( int t, ValueType val, LexLocation loc ) {
    this.token = t; this.yylval = val; this.yylloc = loc;
  }
}

public class LispScriptParser: ShiftReduceParser<ValueType, LexLocation>
{
#pragma warning disable 649
  private static Dictionary<int, string> aliasses;
#pragma warning restore 649
  private static Rule[] rules = new Rule[31];
  private static State[] states = new State[61];
  private static string[] nonTerms = new string[] {
      "declarations", "scriptname", "declaration", "globaldecl", "objectdecl", 
      "scriptdecl", "expression", "constant", "functioncall", "variable", "expressions", 
      "parameter", "parameters", "$accept", };

  static LispScriptParser() {
    states[0] = new State(-2,new int[]{-1,1});
    states[1] = new State(new int[]{46,2,40,5},new int[]{-3,3,-4,4,-5,59,-6,60});
    states[2] = new State(-1);
    states[3] = new State(-3);
    states[4] = new State(-4);
    states[5] = new State(new int[]{47,6,48,28,49,38});
    states[6] = new State(new int[]{50,7});
    states[7] = new State(new int[]{50,8});
    states[8] = new State(new int[]{51,12,52,13,53,14,54,15,40,17,50,24},new int[]{-7,9,-8,11,-9,16,-10,23});
    states[9] = new State(new int[]{41,10});
    states[10] = new State(-7);
    states[11] = new State(-21);
    states[12] = new State(-24);
    states[13] = new State(-25);
    states[14] = new State(-26);
    states[15] = new State(-27);
    states[16] = new State(-22);
    states[17] = new State(new int[]{50,26,51,27},new int[]{-2,18});
    states[18] = new State(new int[]{41,19,51,12,52,13,53,14,54,15,40,17,50,24},new int[]{-11,20,-7,25,-8,11,-9,16,-10,23});
    states[19] = new State(-28);
    states[20] = new State(new int[]{41,21,51,12,52,13,53,14,54,15,40,17,50,24},new int[]{-7,22,-8,11,-9,16,-10,23});
    states[21] = new State(-29);
    states[22] = new State(-20);
    states[23] = new State(-23);
    states[24] = new State(-30);
    states[25] = new State(-19);
    states[26] = new State(-11);
    states[27] = new State(-12);
    states[28] = new State(new int[]{50,29,54,33});
    states[29] = new State(new int[]{50,30});
    states[30] = new State(new int[]{51,31});
    states[31] = new State(new int[]{41,32});
    states[32] = new State(-8);
    states[33] = new State(new int[]{50,34});
    states[34] = new State(new int[]{41,35,51,36});
    states[35] = new State(-9);
    states[36] = new State(new int[]{41,37});
    states[37] = new State(-10);
    states[38] = new State(new int[]{50,39});
    states[39] = new State(new int[]{50,40});
    states[40] = new State(new int[]{40,44,50,26,51,27},new int[]{-2,41});
    states[41] = new State(new int[]{51,12,52,13,53,14,54,15,40,17,50,24},new int[]{-11,42,-7,25,-8,11,-9,16,-10,23});
    states[42] = new State(new int[]{41,43,51,12,52,13,53,14,54,15,40,17,50,24},new int[]{-7,22,-8,11,-9,16,-10,23});
    states[43] = new State(-13);
    states[44] = new State(new int[]{50,26,51,27},new int[]{-2,45});
    states[45] = new State(new int[]{40,46});
    states[46] = new State(new int[]{50,54,48,56},new int[]{-13,47,-12,58});
    states[47] = new State(new int[]{41,48,44,52});
    states[48] = new State(new int[]{41,49});
    states[49] = new State(new int[]{51,12,52,13,53,14,54,15,40,17,50,24},new int[]{-11,50,-7,25,-8,11,-9,16,-10,23});
    states[50] = new State(new int[]{41,51,51,12,52,13,53,14,54,15,40,17,50,24},new int[]{-7,22,-8,11,-9,16,-10,23});
    states[51] = new State(-14);
    states[52] = new State(new int[]{50,54,48,56},new int[]{-12,53});
    states[53] = new State(-16);
    states[54] = new State(new int[]{50,55});
    states[55] = new State(-17);
    states[56] = new State(new int[]{50,57});
    states[57] = new State(-18);
    states[58] = new State(-15);
    states[59] = new State(-5);
    states[60] = new State(-6);

    for (int sNo = 0; sNo < states.Length; sNo++) states[sNo].number = sNo;

    rules[1] = new Rule(-14, new int[]{-1,46});
    rules[2] = new Rule(-1, new int[]{});
    rules[3] = new Rule(-1, new int[]{-1,-3});
    rules[4] = new Rule(-3, new int[]{-4});
    rules[5] = new Rule(-3, new int[]{-5});
    rules[6] = new Rule(-3, new int[]{-6});
    rules[7] = new Rule(-4, new int[]{40,47,50,50,-7,41});
    rules[8] = new Rule(-5, new int[]{40,48,50,50,51,41});
    rules[9] = new Rule(-5, new int[]{40,48,54,50,41});
    rules[10] = new Rule(-5, new int[]{40,48,54,50,51,41});
    rules[11] = new Rule(-2, new int[]{50});
    rules[12] = new Rule(-2, new int[]{51});
    rules[13] = new Rule(-6, new int[]{40,49,50,50,-2,-11,41});
    rules[14] = new Rule(-6, new int[]{40,49,50,50,40,-2,40,-13,41,41,-11,41});
    rules[15] = new Rule(-13, new int[]{-12});
    rules[16] = new Rule(-13, new int[]{-13,44,-12});
    rules[17] = new Rule(-12, new int[]{50,50});
    rules[18] = new Rule(-12, new int[]{48,50});
    rules[19] = new Rule(-11, new int[]{-7});
    rules[20] = new Rule(-11, new int[]{-11,-7});
    rules[21] = new Rule(-7, new int[]{-8});
    rules[22] = new Rule(-7, new int[]{-9});
    rules[23] = new Rule(-7, new int[]{-10});
    rules[24] = new Rule(-8, new int[]{51});
    rules[25] = new Rule(-8, new int[]{52});
    rules[26] = new Rule(-8, new int[]{53});
    rules[27] = new Rule(-8, new int[]{54});
    rules[28] = new Rule(-9, new int[]{40,-2,41});
    rules[29] = new Rule(-9, new int[]{40,-2,-11,41});
    rules[30] = new Rule(-10, new int[]{50});
  }

  protected override void Initialize() {
    this.InitSpecialTokens((int)LispScriptTokens.error, (int)LispScriptTokens.EOF);
    this.InitStates(states);
    this.InitRules(rules);
    this.InitNonTerminals(nonTerms);
  }

  protected override void DoAction(int action)
  {
#pragma warning disable 162, 1522
    switch (action)
    {
      case 3: // declarations -> declarations, declaration
#line 37 "Blam\Scripting\Analysis\LispScriptParser.y"
{ Nodes.Add(ValueStack[ValueStack.Depth-1].Node); }
        break;
      case 7: // globaldecl -> '(', GLOBAL, NAME, NAME, expression, ')'
#line 46 "Blam\Scripting\Analysis\LispScriptParser.y"
{ CurrentSemanticValue.Node = new GlobalDefinitionNode(ValueStack[ValueStack.Depth-3].StringValue, ValueStack[ValueStack.Depth-4].StringValue, ValueStack[ValueStack.Depth-2].Node); }
        break;
      case 8: // objectdecl -> '(', OBJECT, NAME, NAME, FLOAT, ')'
#line 50 "Blam\Scripting\Analysis\LispScriptParser.y"
{ CurrentSemanticValue.Node = new ObjectDefinitionNode(ValueStack[ValueStack.Depth-3].StringValue, ValueStack[ValueStack.Depth-4].StringValue, (int)ValueStack[ValueStack.Depth-2].FloatValue); }
        break;
      case 9: // objectdecl -> '(', OBJECT, NONE, NAME, ')'
#line 52 "Blam\Scripting\Analysis\LispScriptParser.y"
{ CurrentSemanticValue.Node = new ObjectDefinitionNode(ValueStack[ValueStack.Depth-2].StringValue, "none", -1); }
        break;
      case 10: // objectdecl -> '(', OBJECT, NONE, NAME, FLOAT, ')'
#line 54 "Blam\Scripting\Analysis\LispScriptParser.y"
{ CurrentSemanticValue.Node = new ObjectDefinitionNode(ValueStack[ValueStack.Depth-3].StringValue, "none", (int)ValueStack[ValueStack.Depth-2].FloatValue); }
        break;
      case 12: // scriptname -> FLOAT
#line 60 "Blam\Scripting\Analysis\LispScriptParser.y"
{ CurrentSemanticValue.StringValue = ValueStack[ValueStack.Depth-1].FloatValue.ToString(); }
        break;
      case 13: // scriptdecl -> '(', SCRIPT, NAME, NAME, scriptname, expressions, ')'
#line 64 "Blam\Scripting\Analysis\LispScriptParser.y"
{
#line 65 "Blam\Scripting\Analysis\LispScriptParser.y"
                   var def = new ScriptDefinitionNode(ValueStack[ValueStack.Depth-3].StringValue, ValueStack[ValueStack.Depth-5].StringValue, ValueStack[ValueStack.Depth-4].StringValue);
#line 66 "Blam\Scripting\Analysis\LispScriptParser.y"
                   def.Nodes.AddRange(ValueStack[ValueStack.Depth-2].NodeList);
#line 67 "Blam\Scripting\Analysis\LispScriptParser.y"
                   CurrentSemanticValue.Node = def;
#line 68 "Blam\Scripting\Analysis\LispScriptParser.y"
               }
        break;
      case 14: // scriptdecl -> '(', SCRIPT, NAME, NAME, '(', scriptname, '(', parameters, ')', 
               //               ')', expressions, ')'
#line 70 "Blam\Scripting\Analysis\LispScriptParser.y"
{
#line 71 "Blam\Scripting\Analysis\LispScriptParser.y"
                   var def = new ScriptDefinitionNode(ValueStack[ValueStack.Depth-7].StringValue, ValueStack[ValueStack.Depth-10].StringValue, ValueStack[ValueStack.Depth-9].StringValue);
#line 72 "Blam\Scripting\Analysis\LispScriptParser.y"
                   def.Parameters.AddRange(ValueStack[ValueStack.Depth-5].ParamList);
#line 73 "Blam\Scripting\Analysis\LispScriptParser.y"
                   def.Nodes.AddRange(ValueStack[ValueStack.Depth-2].NodeList);
#line 74 "Blam\Scripting\Analysis\LispScriptParser.y"
                   CurrentSemanticValue.Node = def;
#line 75 "Blam\Scripting\Analysis\LispScriptParser.y"
               }
        break;
      case 15: // parameters -> parameter
#line 79 "Blam\Scripting\Analysis\LispScriptParser.y"
{ CurrentSemanticValue.ParamList = new List<ScriptDefinitionParam>(); CurrentSemanticValue.ParamList.Add(ValueStack[ValueStack.Depth-1].Parameter); }
        break;
      case 16: // parameters -> parameters, ',', parameter
#line 81 "Blam\Scripting\Analysis\LispScriptParser.y"
{ CurrentSemanticValue.ParamList = ValueStack[ValueStack.Depth-3].ParamList; CurrentSemanticValue.ParamList.Add(ValueStack[ValueStack.Depth-1].Parameter); }
        break;
      case 17: // parameter -> NAME, NAME
#line 85 "Blam\Scripting\Analysis\LispScriptParser.y"
{ CurrentSemanticValue.Parameter = new ScriptDefinitionParam(ValueStack[ValueStack.Depth-1].StringValue, ValueStack[ValueStack.Depth-2].StringValue); }
        break;
      case 18: // parameter -> OBJECT, NAME
#line 88 "Blam\Scripting\Analysis\LispScriptParser.y"
{ CurrentSemanticValue.Parameter = new ScriptDefinitionParam(ValueStack[ValueStack.Depth-1].StringValue, "object"); }
        break;
      case 19: // expressions -> expression
#line 92 "Blam\Scripting\Analysis\LispScriptParser.y"
{ CurrentSemanticValue.NodeList = new List<IScriptNode>(); CurrentSemanticValue.NodeList.Add(ValueStack[ValueStack.Depth-1].Node); }
        break;
      case 20: // expressions -> expressions, expression
#line 94 "Blam\Scripting\Analysis\LispScriptParser.y"
{ CurrentSemanticValue.NodeList = ValueStack[ValueStack.Depth-2].NodeList; CurrentSemanticValue.NodeList.Add(ValueStack[ValueStack.Depth-1].Node); }
        break;
      case 24: // constant -> FLOAT
#line 103 "Blam\Scripting\Analysis\LispScriptParser.y"
{ CurrentSemanticValue.Node = new ConstantNode(ValueStack[ValueStack.Depth-1].FloatValue); }
        break;
      case 25: // constant -> STRING
#line 105 "Blam\Scripting\Analysis\LispScriptParser.y"
{ CurrentSemanticValue.Node = new ConstantNode(ValueStack[ValueStack.Depth-1].StringValue); }
        break;
      case 26: // constant -> BOOLEAN
#line 107 "Blam\Scripting\Analysis\LispScriptParser.y"
{ CurrentSemanticValue.Node = new ConstantNode(ValueStack[ValueStack.Depth-1].BooleanValue); }
        break;
      case 27: // constant -> NONE
#line 109 "Blam\Scripting\Analysis\LispScriptParser.y"
{ CurrentSemanticValue.Node = new ConstantNode(); }
        break;
      case 28: // functioncall -> '(', scriptname, ')'
#line 113 "Blam\Scripting\Analysis\LispScriptParser.y"
{ CurrentSemanticValue.Node = new FunctionCallNode(ValueStack[ValueStack.Depth-2].StringValue); }
        break;
      case 29: // functioncall -> '(', scriptname, expressions, ')'
#line 115 "Blam\Scripting\Analysis\LispScriptParser.y"
{
#line 116 "Blam\Scripting\Analysis\LispScriptParser.y"
                     var call = new FunctionCallNode(ValueStack[ValueStack.Depth-3].StringValue);
#line 117 "Blam\Scripting\Analysis\LispScriptParser.y"
                     call.Arguments.AddRange(ValueStack[ValueStack.Depth-2].NodeList);
#line 118 "Blam\Scripting\Analysis\LispScriptParser.y"
                     CurrentSemanticValue.Node = call;
#line 119 "Blam\Scripting\Analysis\LispScriptParser.y"
                 }
        break;
      case 30: // variable -> NAME
#line 123 "Blam\Scripting\Analysis\LispScriptParser.y"
{ CurrentSemanticValue.Node = new VariableReferenceNode(ValueStack[ValueStack.Depth-1].StringValue); }
        break;
    }
#pragma warning restore 162, 1522
  }

  protected override string TerminalToString(int terminal)
  {
    if (aliasses != null && aliasses.ContainsKey(terminal))
        return aliasses[terminal];
    else if (((LispScriptTokens)terminal).ToString() != terminal.ToString(CultureInfo.InvariantCulture))
        return ((LispScriptTokens)terminal).ToString();
    else
        return CharToString((char)terminal);
  }

#line 127 "Blam\Scripting\Analysis\LispScriptParser.y"

#line 128 "Blam\Scripting\Analysis\LispScriptParser.y"
public LispScriptParser(LispScriptScanner sc)
#line 129 "Blam\Scripting\Analysis\LispScriptParser.y"
	: base(sc)
#line 130 "Blam\Scripting\Analysis\LispScriptParser.y"
{
#line 131 "Blam\Scripting\Analysis\LispScriptParser.y"
    Nodes = new List<IScriptNode>();
#line 132 "Blam\Scripting\Analysis\LispScriptParser.y"
}
#line 133 "Blam\Scripting\Analysis\LispScriptParser.y"

#line 134 "Blam\Scripting\Analysis\LispScriptParser.y"
public List<IScriptNode> Nodes { get; private set; }
}
}
