//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from BS_Reach.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IBS_ReachListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public partial class BS_ReachBaseListener : IBS_ReachListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="BS_ReachParser.hsc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHsc([NotNull] BS_ReachParser.HscContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BS_ReachParser.hsc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHsc([NotNull] BS_ReachParser.HscContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BS_ReachParser.gloDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGloDecl([NotNull] BS_ReachParser.GloDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BS_ReachParser.gloDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGloDecl([NotNull] BS_ReachParser.GloDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BS_ReachParser.scriDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterScriDecl([NotNull] BS_ReachParser.ScriDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BS_ReachParser.scriDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitScriDecl([NotNull] BS_ReachParser.ScriDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BS_ReachParser.scriptParams"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterScriptParams([NotNull] BS_ReachParser.ScriptParamsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BS_ReachParser.scriptParams"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitScriptParams([NotNull] BS_ReachParser.ScriptParamsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BS_ReachParser.call"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCall([NotNull] BS_ReachParser.CallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BS_ReachParser.call"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCall([NotNull] BS_ReachParser.CallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BS_ReachParser.funcID"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncID([NotNull] BS_ReachParser.FuncIDContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BS_ReachParser.funcID"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncID([NotNull] BS_ReachParser.FuncIDContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BS_ReachParser.gloRef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGloRef([NotNull] BS_ReachParser.GloRefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BS_ReachParser.gloRef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGloRef([NotNull] BS_ReachParser.GloRefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BS_ReachParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpr([NotNull] BS_ReachParser.ExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BS_ReachParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpr([NotNull] BS_ReachParser.ExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BS_ReachParser.retType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRetType([NotNull] BS_ReachParser.RetTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BS_ReachParser.retType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRetType([NotNull] BS_ReachParser.RetTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BS_ReachParser.lit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLit([NotNull] BS_ReachParser.LitContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BS_ReachParser.lit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLit([NotNull] BS_ReachParser.LitContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
