//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from BS_Reach.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="BS_ReachParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public interface IBS_ReachListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="BS_ReachParser.hsc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHsc([NotNull] BS_ReachParser.HscContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BS_ReachParser.hsc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHsc([NotNull] BS_ReachParser.HscContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BS_ReachParser.gloDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGloDecl([NotNull] BS_ReachParser.GloDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BS_ReachParser.gloDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGloDecl([NotNull] BS_ReachParser.GloDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BS_ReachParser.scriDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterScriDecl([NotNull] BS_ReachParser.ScriDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BS_ReachParser.scriDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitScriDecl([NotNull] BS_ReachParser.ScriDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BS_ReachParser.scriptParams"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterScriptParams([NotNull] BS_ReachParser.ScriptParamsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BS_ReachParser.scriptParams"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitScriptParams([NotNull] BS_ReachParser.ScriptParamsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BS_ReachParser.branch"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBranch([NotNull] BS_ReachParser.BranchContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BS_ReachParser.branch"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBranch([NotNull] BS_ReachParser.BranchContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BS_ReachParser.call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCall([NotNull] BS_ReachParser.CallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BS_ReachParser.call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCall([NotNull] BS_ReachParser.CallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BS_ReachParser.scriptID"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterScriptID([NotNull] BS_ReachParser.ScriptIDContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BS_ReachParser.scriptID"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitScriptID([NotNull] BS_ReachParser.ScriptIDContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BS_ReachParser.funcID"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFuncID([NotNull] BS_ReachParser.FuncIDContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BS_ReachParser.funcID"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFuncID([NotNull] BS_ReachParser.FuncIDContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BS_ReachParser.gloRef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGloRef([NotNull] BS_ReachParser.GloRefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BS_ReachParser.gloRef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGloRef([NotNull] BS_ReachParser.GloRefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BS_ReachParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpr([NotNull] BS_ReachParser.ExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BS_ReachParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpr([NotNull] BS_ReachParser.ExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BS_ReachParser.retType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRetType([NotNull] BS_ReachParser.RetTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BS_ReachParser.retType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRetType([NotNull] BS_ReachParser.RetTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BS_ReachParser.lit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLit([NotNull] BS_ReachParser.LitContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BS_ReachParser.lit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLit([NotNull] BS_ReachParser.LitContext context);
}
