//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from d:\Dev\Antlr\BS_Reach.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IBS_ReachListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
public partial class BS_ReachBaseListener : IBS_ReachListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="BS_ReachParser.hsc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHsc([NotNull] BS_ReachParser.HscContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BS_ReachParser.hsc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHsc([NotNull] BS_ReachParser.HscContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BS_ReachParser.globalDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGlobalDeclaration([NotNull] BS_ReachParser.GlobalDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BS_ReachParser.globalDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGlobalDeclaration([NotNull] BS_ReachParser.GlobalDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BS_ReachParser.scriptDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterScriptDeclaration([NotNull] BS_ReachParser.ScriptDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BS_ReachParser.scriptDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitScriptDeclaration([NotNull] BS_ReachParser.ScriptDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BS_ReachParser.scriptParameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterScriptParameters([NotNull] BS_ReachParser.ScriptParametersContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BS_ReachParser.scriptParameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitScriptParameters([NotNull] BS_ReachParser.ScriptParametersContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BS_ReachParser.cond"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCond([NotNull] BS_ReachParser.CondContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BS_ReachParser.cond"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCond([NotNull] BS_ReachParser.CondContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BS_ReachParser.branch"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBranch([NotNull] BS_ReachParser.BranchContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BS_ReachParser.branch"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBranch([NotNull] BS_ReachParser.BranchContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BS_ReachParser.call"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCall([NotNull] BS_ReachParser.CallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BS_ReachParser.call"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCall([NotNull] BS_ReachParser.CallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BS_ReachParser.condGroup"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCondGroup([NotNull] BS_ReachParser.CondGroupContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BS_ReachParser.condGroup"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCondGroup([NotNull] BS_ReachParser.CondGroupContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BS_ReachParser.parameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameter([NotNull] BS_ReachParser.ParameterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BS_ReachParser.parameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameter([NotNull] BS_ReachParser.ParameterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BS_ReachParser.scriptID"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterScriptID([NotNull] BS_ReachParser.ScriptIDContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BS_ReachParser.scriptID"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitScriptID([NotNull] BS_ReachParser.ScriptIDContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BS_ReachParser.callID"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCallID([NotNull] BS_ReachParser.CallIDContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BS_ReachParser.callID"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCallID([NotNull] BS_ReachParser.CallIDContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BS_ReachParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression([NotNull] BS_ReachParser.ExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BS_ReachParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression([NotNull] BS_ReachParser.ExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BS_ReachParser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLiteral([NotNull] BS_ReachParser.LiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BS_ReachParser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLiteral([NotNull] BS_ReachParser.LiteralContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
