//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from d:\Dev\Antlr\HS_Gen1.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IHS_Gen1Listener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
public partial class HS_Gen1BaseListener : IHS_Gen1Listener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="HS_Gen1Parser.hsc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHsc([NotNull] HS_Gen1Parser.HscContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HS_Gen1Parser.hsc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHsc([NotNull] HS_Gen1Parser.HscContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="HS_Gen1Parser.globalDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGlobalDeclaration([NotNull] HS_Gen1Parser.GlobalDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HS_Gen1Parser.globalDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGlobalDeclaration([NotNull] HS_Gen1Parser.GlobalDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="HS_Gen1Parser.scriptDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterScriptDeclaration([NotNull] HS_Gen1Parser.ScriptDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HS_Gen1Parser.scriptDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitScriptDeclaration([NotNull] HS_Gen1Parser.ScriptDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="HS_Gen1Parser.scriptParameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterScriptParameters([NotNull] HS_Gen1Parser.ScriptParametersContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HS_Gen1Parser.scriptParameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitScriptParameters([NotNull] HS_Gen1Parser.ScriptParametersContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="HS_Gen1Parser.cond"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCond([NotNull] HS_Gen1Parser.CondContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HS_Gen1Parser.cond"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCond([NotNull] HS_Gen1Parser.CondContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="HS_Gen1Parser.branch"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBranch([NotNull] HS_Gen1Parser.BranchContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HS_Gen1Parser.branch"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBranch([NotNull] HS_Gen1Parser.BranchContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="HS_Gen1Parser.call"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCall([NotNull] HS_Gen1Parser.CallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HS_Gen1Parser.call"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCall([NotNull] HS_Gen1Parser.CallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="HS_Gen1Parser.condGroup"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCondGroup([NotNull] HS_Gen1Parser.CondGroupContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HS_Gen1Parser.condGroup"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCondGroup([NotNull] HS_Gen1Parser.CondGroupContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="HS_Gen1Parser.parameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameter([NotNull] HS_Gen1Parser.ParameterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HS_Gen1Parser.parameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameter([NotNull] HS_Gen1Parser.ParameterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="HS_Gen1Parser.scriptID"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterScriptID([NotNull] HS_Gen1Parser.ScriptIDContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HS_Gen1Parser.scriptID"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitScriptID([NotNull] HS_Gen1Parser.ScriptIDContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="HS_Gen1Parser.callID"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCallID([NotNull] HS_Gen1Parser.CallIDContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HS_Gen1Parser.callID"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCallID([NotNull] HS_Gen1Parser.CallIDContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="HS_Gen1Parser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression([NotNull] HS_Gen1Parser.ExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HS_Gen1Parser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression([NotNull] HS_Gen1Parser.ExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="HS_Gen1Parser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLiteral([NotNull] HS_Gen1Parser.LiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HS_Gen1Parser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLiteral([NotNull] HS_Gen1Parser.LiteralContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
