//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from d:\Dev\Antlr\HS_Gen1.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="HS_Gen1Parser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
public interface IHS_Gen1Listener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="HS_Gen1Parser.hsc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHsc([NotNull] HS_Gen1Parser.HscContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HS_Gen1Parser.hsc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHsc([NotNull] HS_Gen1Parser.HscContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HS_Gen1Parser.globalDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGlobalDeclaration([NotNull] HS_Gen1Parser.GlobalDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HS_Gen1Parser.globalDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGlobalDeclaration([NotNull] HS_Gen1Parser.GlobalDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HS_Gen1Parser.scriptDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterScriptDeclaration([NotNull] HS_Gen1Parser.ScriptDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HS_Gen1Parser.scriptDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitScriptDeclaration([NotNull] HS_Gen1Parser.ScriptDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HS_Gen1Parser.scriptParameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterScriptParameters([NotNull] HS_Gen1Parser.ScriptParametersContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HS_Gen1Parser.scriptParameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitScriptParameters([NotNull] HS_Gen1Parser.ScriptParametersContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HS_Gen1Parser.cond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCond([NotNull] HS_Gen1Parser.CondContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HS_Gen1Parser.cond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCond([NotNull] HS_Gen1Parser.CondContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HS_Gen1Parser.branch"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBranch([NotNull] HS_Gen1Parser.BranchContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HS_Gen1Parser.branch"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBranch([NotNull] HS_Gen1Parser.BranchContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HS_Gen1Parser.call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCall([NotNull] HS_Gen1Parser.CallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HS_Gen1Parser.call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCall([NotNull] HS_Gen1Parser.CallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HS_Gen1Parser.condGroup"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCondGroup([NotNull] HS_Gen1Parser.CondGroupContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HS_Gen1Parser.condGroup"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCondGroup([NotNull] HS_Gen1Parser.CondGroupContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HS_Gen1Parser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameter([NotNull] HS_Gen1Parser.ParameterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HS_Gen1Parser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameter([NotNull] HS_Gen1Parser.ParameterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HS_Gen1Parser.scriptID"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterScriptID([NotNull] HS_Gen1Parser.ScriptIDContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HS_Gen1Parser.scriptID"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitScriptID([NotNull] HS_Gen1Parser.ScriptIDContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HS_Gen1Parser.callID"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCallID([NotNull] HS_Gen1Parser.CallIDContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HS_Gen1Parser.callID"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCallID([NotNull] HS_Gen1Parser.CallIDContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HS_Gen1Parser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] HS_Gen1Parser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HS_Gen1Parser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] HS_Gen1Parser.ExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HS_Gen1Parser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLiteral([NotNull] HS_Gen1Parser.LiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HS_Gen1Parser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLiteral([NotNull] HS_Gen1Parser.LiteralContext context);
}
